// Mocks generated by Mockito 5.4.6 from annotations
// in key_starter/test/features/note_recognition/presentation/providers/note_recognition_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dartz/dartz.dart' as _i3;
import 'package:key_starter/core/errors/failures.dart' as _i5;
import 'package:key_starter/features/note_recognition/domain/entities/note.dart'
    as _i6;
import 'package:key_starter/features/note_recognition/domain/repositories/note_recognition_repository.dart'
    as _i2;
import 'package:key_starter/features/note_recognition/domain/usecases/recognize_note_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNoteRecognitionRepository_0 extends _i1.SmartFake
    implements _i2.NoteRecognitionRepository {
  _FakeNoteRecognitionRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecognizeNoteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecognizeNoteUseCase extends _i1.Mock
    implements _i4.RecognizeNoteUseCase {
  MockRecognizeNoteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRecognitionRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRecognitionRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRecognitionRepository);

  @override
  _i3.Either<_i5.Failure, _i6.Note> call(int? midiNumber) =>
      (super.noSuchMethod(
            Invocation.method(#call, [midiNumber]),
            returnValue: _FakeEither_1<_i5.Failure, _i6.Note>(
              this,
              Invocation.method(#call, [midiNumber]),
            ),
          )
          as _i3.Either<_i5.Failure, _i6.Note>);
}
