// Mocks generated by Mockito 5.4.6 from annotations
// in key_starter/test/features/note_recognition/data/repositories/note_recognition_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:key_starter/features/note_recognition/data/datasources/midi_datasource.dart'
    as _i3;
import 'package:key_starter/features/note_recognition/domain/entities/note.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MidiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMidiDataSource extends _i1.Mock implements _i3.MidiDataSource {
  MockMidiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Note noteFromMidiNumber(int? midiNumber) =>
      (super.noSuchMethod(
            Invocation.method(#noteFromMidiNumber, [midiNumber]),
            returnValue: _FakeNote_0(
              this,
              Invocation.method(#noteFromMidiNumber, [midiNumber]),
            ),
          )
          as _i2.Note);
}
